import React from "react";

export const FoodItemData = [
  {
    itemname: "Cheese Burger",
    category: "Fast Food",
    addons: "3",
    price: 120,
    sales: 112,
  },
  {
    itemname: "Pepperoni Pizza",
    category: "Pizza",
    addons: "2",
    price: 15,
    sales: 98,
  },
  {
    itemname: "Chicken Alfredo Pasta",
    category: "Italian",
    addons: "1",
    price: 18,
    sales: 75,
  },
  {
    itemname: "Caesar Salad",
    category: "Salad",
    addons: "4",
    price: 10,
    sales: 120,
  },
  {
    itemname: "Sushi Combo",
    category: "Japanese",
    addons: "3",
    price: 22,
    sales: 90,
  },
  {
    itemname: "Veggie Wrap",
    category: "Vegetarian",
    addons: "2",
    price: 14,
    sales: 80,
  },
  {
    itemname: "BBQ Ribs",
    category: "Barbecue",
    addons: "5",
    price: 25,
    sales: 65,
  },
  {
    itemname: "Shrimp Tacos",
    category: "Mexican",
    addons: "3",
    price: 20,
    sales: 88,
  },
  {
    itemname: "Shrimp Tacos",
    category: "Mexican",
    addons: "3",
    price: 20,
    sales: 88,
  },
  {
    itemname: "Mango Lassi",
    category: "Beverage",
    addons: "1",
    price: 5,
    sales: 150,
  },
  {
    itemname: "Chocolate Brownie Sundae",
    category: "Dessert",
    addons: "2",
    price: 12,
    sales: 50,
  },
  {
    itemname: "Grilled Salmon",
    category: "Seafood",
    addons: "4",
    price: 28,
    sales: 70,
  },
];
